name: Go CI

on:
  push:
    branches: [main, 'feature/**'] # Trigger on push to main and feature branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1 # Specify the Go version you want to use

    - name: Build
      run: go build ./...

    - name: Run tests
      run: go test ./...

    - name: Lint
      run: golangci-lint run